### ISSUE TITLE
Latest version support issues

### ISSUE THREAD

**Issue by hands8142** [DiscordKt/DiscordKt#13]
Hello, I am studying Kotlin and found this package to make a discode bot with Kotlin. I tried to make a nail using this, but it's not supported by the latest kotlin. And if you try to use emoji, gaitway, or mentEmbed, you will have a problem. I am interested in this package. I want it to grow a lot and I know you're still developing a lot at the develop branch. Do you think you'll release the new version?

**Comment by JakeJMattson** [comment]
Hello,
Thanks for your interest in the project. The develop branch is progressing with a snapshot (unfinished) version of a dependency (Kord). For that reason I cannot release this version yet. The develop branch includes [instructions](https://github.com/DiscordKt/DiscordKt/tree/develop#readme) on how to use the snapshot version of DiscordKt if you're interested in trying that.

**Comment by hands8142** [comment]
Thank you for answering me and I will be using the snapshot version while waiting for the official version. I hope this package works well. I will be rooting for you.
