### ISSUE TITLE
Select prompts in conversations don't work anymore

### ISSUE THREAD

**Issue by SarahIsWeird** [DiscordKt/DiscordKt#31]
Since `0.23.5-SNAPSHOT` (including `0.24.0-SNAPSHOT`), select menus in conversations are broken. You can define a selection prompt and it will be shown to the user, but the interaction isn't being processed. `0.23.4` doesn't show this behavior. Buttons still work, only selects are affected.

The receive handler for interaction responses is defined on [line 189 of ConversationBuilder.kt](https://github.com/DiscordKt/DiscordKt/blob/ed61a7cee102eddb805bf93b72aae2a2ee8301bd/src/main/kotlin/me/jakejmattson/discordkt/conversations/ConversationBuilder.kt#L189). The lambda isn't being called for select interactions for some reason, though it is being called for buttons. Sadly I wasn't able to pin down the error any further due to my lack of knowledge of the inner workings.

Example:
```kt
conversation {
  channel.createMessage("Test 1")

  val buttonResponse = promptButton {
    embed {
      content = "This is a test button embed. Interactions with this are being processed."
    }

    buttons {
      button("Foo", null, "foo")
      button("Bar", null, "bar")
    }
  }

  channel.createMessage("The \"$buttonResponse\" button was pressed.")

  val selections = promptSelect {
    content("This is a test select. Interactions with this *aren't* being processed.")

    option("Foobar", "foobar")
    option("Foobaz", "foobaz")
  }

  channel.createMessage("Code after the promptSelect call isn't being called, so this message won't even show.")
  channel.createMessage("Selection: ${selections.joinToString()}")
}
```

This demonstrates that the select prompt is being sent to the user, but anything after that isn't executed anymore due to the interaction not being received. Discord doesn't receive an acknowledgement of the receipt either:

![Discord shows the "This interaction failed." message.](https://egirl.rip/coS3sSz7e4.png?key=LQYsYI8jMYk0KP)

**Comment by JakeJMattson** [comment]
Fixed this in quick and timely manner (🤡)
