### ISSUE TITLE
CPU leak on sending messages

### ISSUE THREAD

**Issue by Zabuzard** [DiscordKt/DiscordKt#32]
## Overview

There seems to be a performance leak when sending messages. I managed to create a minimal example that reproduces the problem.

I am using version **0.23.4**, the project is otherwise completely empty, just this:

```kt
@OptIn(KordPreview::class)
fun main(args: Array<String>) {
    bot(args.first()) {}
}

fun foo() = commands("foo") {
    slash("send") {
        execute {
            respond("okay")

            repeat(10) {
                channel.createMessage("test $it")
            }
        }
    }
}
```

This code sends 10 messages and thats it, the CPU continues to spike up and never recovers again:

![issue](https://i.imgur.com/IRaxP6o.gif)

## Tests

To ensure its actually DiscordKt, I ran the same test with just kord, which could not reproduce it anymore:

```kt
suspend fun main(args: Array<String>) {
    val kord = Kord(args.first())
    kord.createGlobalChatInputCommand("send", "test") {}

    kord.on<ChatInputCommandInteractionCreateEvent> {
        interaction.respondPublic { content = "okay" }

        repeat(10) {
            interaction.channel.createMessage("test $it")
        }
    }

    kord.login()
}
```

In fact, when doing the slash command and message sending with kord, but the bot-setup with DiscordKt, it happens again:

```kt
@OptIn(KordPreview::class)
suspend fun main(args: Array<String>) {
    bot(args.first()) {
        onStart {
            kord.createGlobalChatInputCommand("send", "test") {}

            kord.on<ChatInputCommandInteractionCreateEvent> {
                interaction.respondPublic { content = "okay" }

                repeat(10) {
                    interaction.channel.createMessage("test $it")
                }
            }
        }
    }
}
```

This leads me to the conclusion that there might be some message-listener in DiscordKt running in the background, which goes haywire.

**Comment by Zabuzard** [comment]
I was able to nail it down further. It doesnt matter who sends the messages. Even if the bot doesnt send anything, just by sitting in a server and receiving messages from other users triggers the issues.

**Comment by dizyaa** [comment]
@Zabuzard @JakeJMattson 
a leak occurs if the prefix is empty, because the listener listens for each message or something like that. Changed the empty string to "!" so that there is no leakage if the developer did not set the prefix.

https://github.com/DiscordKt/DiscordKt/pull/33
