### ISSUE TITLE
Feature Request - Conversation Exit handler

### ISSUE THREAD

**Issue by AriestaAgung** [DiscordKt/DiscordKt#35]
Hi,  I think adding event whenever conversation is ending is gonna be great so we can handle what to do when user is exit such as giving some respond()

**Comment by AriestaAgung** [comment]
Currently I tried this to give a respond when exitString is being called.
![image](https://github.com/DiscordKt/DiscordKt/assets/47692907/0102ec2c-3e58-4592-95e0-78541323a856)

**Comment by JakeJMattson** [comment]
Conversations already return an enum of `ConversationResult` when they complete. One of the options is `EXITED` which you should be able to use for this

**Comment by JakeJMattson** [comment]
Closing with the assumption that the previous comment will resolve this. Feel free to ask in the discord if you have trouble implementing it or if I misunderstood your issue.
