### ISSUE TITLE
Gateway closed: 4014 Disallowed intent(s) when configure/intents is set to none

### ISSUE THREAD

**Issue by shawnrc** [DiscordKt/DiscordKt#36]
Hey 👋  I'm trying my hand at my very first Discord bot and I've run into an issue where I (I'm pretty sure) I don't need the Message Content intent, but DiscordKt always requests it, even when I have the bot defined as such:

```kotlin
bot(token) {
  configure {
    intents = Intents.none
  }
}
``` 
It looks like on [`Bot.kt#L112`](https://github.com/DiscordKt/DiscordKt/blob/b845d37cc993f1b510c563d006db6ce253da1608/src/main/kotlin/me/jakejmattson/discordkt/dsl/Bot.kt#L112), `intents` is set to `intents + intentsOf<MessageCreateEvent>() + intentsOf<InteractionCreateEvent>()`.

In [`kord/kord-core/.../Util.kt#L407-L411`](https://github.com/kordlib/kord/blob/main/core/src/commonMain/kotlin/Util.kt#L407-L411), `MessageCreateEvent` at least always adds `GuildMessages`, `DirectMessages`, and `MessageContent`. 

That said, I'm definitely pretty new to this—apologies if I've misunderstood something about Intents or the Discord Bot API at large. I figure the fix here would be to change how intents is populated, but it may be difficult to do so without breaking backcompat. Maybe we could have a new setter on SimpleConfiguration that allows consumers to fully override the set of requested intents, though I'm not sure what you would call it.

**Comment by dizyaa** [comment]
@JakeJMattson we can just replace default parametr in SimpleConfiguration? 
<img width="874" alt="image" src="https://github.com/DiscordKt/DiscordKt/assets/53047160/60417bd1-d71c-408d-b796-8b264d53a251">

**Comment by JakeJMattson** [comment]
@dizyaa 
The current default is stuff used internally, but removing `MessageCreateEvent` is fine. Most people are using slash now anyway. There's a branch for removing all the text stuff and making it 100% slash/interactions but I'm still not sure if I want to commit to that yet

**Comment by dizyaa** [comment]
@JakeJMattson 
But leaving a configuration that cannot be changed is not entirely correct. I suggest giving the user the ability to change the default configuration. Or we can just remove defaults intents.
